/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedRecipesRouteRouteImport } from './routes/_authenticated/recipes/route'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes/index'
import { Route as AuthenticatedPayrollIndexRouteImport } from './routes/_authenticated/payroll/index'
import { Route as AuthenticatedRecipesRecipeSlugRouteImport } from './routes/_authenticated/recipes/$recipeSlug'
import { Route as AuthenticatedPayrollEmployeeEmployeeIdRouteImport } from './routes/_authenticated/payroll/employee/$employeeId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesRouteRoute =
  AuthenticatedRecipesRouteRouteImport.update({
    id: '/recipes',
    path: '/recipes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecipesRouteRoute,
  } as any)
const AuthenticatedPayrollIndexRoute =
  AuthenticatedPayrollIndexRouteImport.update({
    id: '/payroll/',
    path: '/payroll/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesRecipeSlugRoute =
  AuthenticatedRecipesRecipeSlugRouteImport.update({
    id: '/$recipeSlug',
    path: '/$recipeSlug',
    getParentRoute: () => AuthenticatedRecipesRouteRoute,
  } as any)
const AuthenticatedPayrollEmployeeEmployeeIdRoute =
  AuthenticatedPayrollEmployeeEmployeeIdRouteImport.update({
    id: '/payroll/employee/$employeeId',
    path: '/payroll/employee/$employeeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/recipes': typeof AuthenticatedRecipesRouteRouteWithChildren
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/recipes/$recipeSlug': typeof AuthenticatedRecipesRecipeSlugRoute
  '/payroll': typeof AuthenticatedPayrollIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/payroll/employee/$employeeId': typeof AuthenticatedPayrollEmployeeEmployeeIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/recipes/$recipeSlug': typeof AuthenticatedRecipesRecipeSlugRoute
  '/payroll': typeof AuthenticatedPayrollIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
  '/payroll/employee/$employeeId': typeof AuthenticatedPayrollEmployeeEmployeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRouteRouteWithChildren
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/recipes/$recipeSlug': typeof AuthenticatedRecipesRecipeSlugRoute
  '/_authenticated/payroll/': typeof AuthenticatedPayrollIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/_authenticated/payroll/employee/$employeeId': typeof AuthenticatedPayrollEmployeeEmployeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/recipes'
    | '/change-password'
    | '/dashboard'
    | '/employees'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/'
    | '/recipes/$recipeSlug'
    | '/payroll'
    | '/recipes/'
    | '/payroll/employee/$employeeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/change-password'
    | '/dashboard'
    | '/employees'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/'
    | '/recipes/$recipeSlug'
    | '/payroll'
    | '/recipes'
    | '/payroll/employee/$employeeId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/recipes'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/profile'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/recipes/$recipeSlug'
    | '/_authenticated/payroll/'
    | '/_authenticated/recipes/'
    | '/_authenticated/payroll/employee/$employeeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRecipesRouteRoute
    }
    '/_authenticated/payroll/': {
      id: '/_authenticated/payroll/'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes/$recipeSlug': {
      id: '/_authenticated/recipes/$recipeSlug'
      path: '/$recipeSlug'
      fullPath: '/recipes/$recipeSlug'
      preLoaderRoute: typeof AuthenticatedRecipesRecipeSlugRouteImport
      parentRoute: typeof AuthenticatedRecipesRouteRoute
    }
    '/_authenticated/payroll/employee/$employeeId': {
      id: '/_authenticated/payroll/employee/$employeeId'
      path: '/payroll/employee/$employeeId'
      fullPath: '/payroll/employee/$employeeId'
      preLoaderRoute: typeof AuthenticatedPayrollEmployeeEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRecipesRouteRouteChildren {
  AuthenticatedRecipesRecipeSlugRoute: typeof AuthenticatedRecipesRecipeSlugRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
}

const AuthenticatedRecipesRouteRouteChildren: AuthenticatedRecipesRouteRouteChildren =
  {
    AuthenticatedRecipesRecipeSlugRoute: AuthenticatedRecipesRecipeSlugRoute,
    AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
  }

const AuthenticatedRecipesRouteRouteWithChildren =
  AuthenticatedRecipesRouteRoute._addFileChildren(
    AuthenticatedRecipesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRecipesRouteRoute: typeof AuthenticatedRecipesRouteRouteWithChildren
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPayrollIndexRoute: typeof AuthenticatedPayrollIndexRoute
  AuthenticatedPayrollEmployeeEmployeeIdRoute: typeof AuthenticatedPayrollEmployeeEmployeeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRecipesRouteRoute: AuthenticatedRecipesRouteRouteWithChildren,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPayrollIndexRoute: AuthenticatedPayrollIndexRoute,
  AuthenticatedPayrollEmployeeEmployeeIdRoute:
    AuthenticatedPayrollEmployeeEmployeeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
